licitacoes:
  url-captura-itens: "http://comprasnet.gov.br/ConsultaLicitacoes/download/download_editais_detalhe.asp"
  url-captura-licitacoes: "http://comprasnet.gov.br/ConsultaLicitacoes/ConsLicitacaoDia.asp?pagina="

spring:
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.community.dialect.SQLiteDialect

  datasource:
    url: jdbc:sqlite:licitacoes.db
    driverClassName: org.sqlite.JDBC

